# Generated by Django 3.0.8 on 2021-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=50)),
                ('experience', models.IntegerField(max_length=50)),
                ('language', models.CharField(max_length=10)),
                ('qualification', models.CharField(default='', max_length=200)),
                ('cv', models.FileField(upload_to='nurse/doc')),
            ],
        ),
    ]
