# Generated by Django 3.0.8 on 2021-01-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nurse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='language',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10),
        ),
    ]
